# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
      timezone: "Asia/Manila"
    target-branch: "develop"
    labels:
      - "github-actions"
    reviewers:
      - "alphacoma18"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
      timezone: "Asia/Manila"
    target-branch: "develop"
    labels:
      - "yarn"
      - "dependencies"
    reviewers:
      - "alphacoma18"
